// Ícones dos itens do bichinho, em pixel.
//
// Cada um é um desenho de 32x32 escrito como texto: cada letra é uma cor do mapa,
// espaço é vazio. Pra item pequeno isso é mais rápido de escrever (e de ajustar)
// do que compor formas — e continua sendo pixel de verdade, sem arquivo de imagem.

const P = {
  o: '#3b2b26', // contorno
  w: '#fffaf3',
  r: '#e8879b',
  R: '#c9607a',
  g: '#9cbf9a',
  G: '#6f9c6d',
  y: '#f2b33d',
  Y: '#d99a24',
  b: '#8a5f3c',
  B: '#5f4028',
  c: '#a8cde0',
  k: '#4a3f66',
  p: '#c9b6e8',
  s: '#e9dcc6',
}

// 16x16, desenhado em dobro na hora de pintar
const SPRITES = {
  // --- comida
  pet_petisco: [
    '                ',
    '                ',
    '      oooo      ',
    '     obbbbo     ',
    '    obYYYYbo    ',
    '   obYyyyyYbo   ',
    '   obyyyyyybo   ',
    '   obyyRRyybo   ',
    '   obyyyyyybo   ',
    '    obyyyybo    ',
    '     obbbbo     ',
    '      oooo      ',
    '                ',
    '                ',
    '                ',
    '                ',
  ],
  pet_racao: [
    '                ',
    '    oooooooo    ',
    '   osssssssso   ',
    '   osbybybyso   ',
    '   osybybybso   ',
    '   osbybybyso   ',
    '   osssssssso   ',
    '    oooooooo    ',
    '   obbbbbbbbo   ',
    '  obYbYbYbYbYo  ',
    '  obbbbbbbbbbo  ',
    '  obYbYbYbYbYo  ',
    '  obbbbbbbbbbo  ',
    '   oooooooooo   ',
    '                ',
    '                ',
  ],
  pet_bolo: [
    '       o        ',
    '      oyo       ',
    '       o        ',
    '    oooooooo    ',
    '   owwwwwwwwo   ',
    '   owrwrwrwwo   ',
    '  oooooooooooo  ',
    '  orrrrrrrrrro  ',
    '  orwrwrwrwrro  ',
    '  oooooooooooo  ',
    '  owwwwwwwwwwo  ',
    '  owsswsswswwo  ',
    '  oooooooooooo  ',
    '                ',
    '                ',
    '                ',
  ],
  pet_sushi: [
    '                ',
    '                ',
    '    oooooooo    ',
    '   okkkkkkkko   ',
    '   okwwwwwwko   ',
    '   okwrrrrwko   ',
    '   okwrRRrwko   ',
    '   okwrrrrwko   ',
    '   okwwwwwwko   ',
    '   okkkkkkkko   ',
    '    oooooooo    ',
    '   obbbbbbbbo   ',
    '    oooooooo    ',
    '                ',
    '                ',
    '                ',
  ],
  pet_banho_kit: [
    '                ',
    '     oooo       ',
    '    occcco      ',
    '   occwwcco     ',
    '   occcccco     ',
    '   occcccco     ',
    '   occcccco     ',
    '   oooooooo     ',
    '  ogggggggggo   ',
    '  ogwgwgwgwgo   ',
    '  oggggggggoo   ',
    '  ogggggggggo   ',
    '  ooooooooooo   ',
    '                ',
    '                ',
    '                ',
  ],
  // --- brinquedos
  pet_bolinha: [
    '                ',
    '                ',
    '     oooooo     ',
    '    orrrrrro    ',
    '   orwwrrrrro   ',
    '  orwwrrrrrrro  ',
    '  orrrrrrrrrro  ',
    '  orrrRRRrrrro  ',
    '  orrRRRRRrrro  ',
    '  orrrRRRrrrro  ',
    '   orrrrrrrro   ',
    '    orrrrrro    ',
    '     oooooo     ',
    '                ',
    '                ',
    '                ',
  ],
  pet_ossinho: [
    '                ',
    '                ',
    '   oo      oo   ',
    '  owwo    owwo  ',
    ' owwwwoooowwwwo ',
    ' owwwwwwwwwwwwo ',
    ' owwwwwwwwwwwwo ',
    ' owwwwoooowwwwo ',
    '  owwo    owwo  ',
    '   oo      oo   ',
    '                ',
    '                ',
    '                ',
    '                ',
    '                ',
    '                ',
  ],
  pet_varinha: [
    '            oo  ',
    '           obbo ',
    '          obbo  ',
    '         obbo   ',
    '        obbo    ',
    '       obbo     ',
    '      obbo      ',
    '     obbo       ',
    '    oppo        ',
    '   oppo         ',
    '  oppo   opo    ',
    ' opo    oppo    ',
    ' oo    oppo     ',
    '      opo       ',
    '                ',
    '                ',
  ],
  pet_almofada: [
    '                ',
    '                ',
    '   oooooooooo   ',
    '  oppppppppppo  ',
    ' oppwppppppwppo ',
    ' opppppppppppo  ',
    ' oppppppppppppo ',
    ' oppppppppppppo ',
    ' opppppppppppo  ',
    ' oppwppppppwppo ',
    '  oppppppppppo  ',
    '   oooooooooo   ',
    '                ',
    '                ',
    '                ',
    '                ',
  ],
  // --- acessórios
  pet_coleira: [
    '                ',
    '    oooooooo    ',
    '   orrrrrrrro   ',
    '  orRRRRRRRRro  ',
    '  orrrrrrrrrro  ',
    '   orrrrrrrro   ',
    '    ooo  ooo    ',
    '      oyyo      ',
    '     oyyyyo     ',
    '     oyyyyo     ',
    '      oyyo      ',
    '       oo       ',
    '                ',
    '                ',
    '                ',
    '                ',
  ],
  pet_gravata: [
    '                ',
    '   oo      oo   ',
    '  okko    okko  ',
    '   okkooookko   ',
    '    okkkkkko    ',
    '     okkkko     ',
    '      okko      ',
    '     okkkko     ',
    '    okkkkkko    ',
    '   okkkkkkkko   ',
    '   okkkkkkkko   ',
    '    okkkkkko    ',
    '     oooooo     ',
    '                ',
    '                ',
    '                ',
  ],
  pet_chapeu: [
    '                ',
    '                ',
    '     oooooo     ',
    '    okkkkkko    ',
    '    okkkkkko    ',
    '    oyyyyyyo    ',
    '  oookkkkkkooo  ',
    ' okkkkkkkkkkkko ',
    ' okkkkkkkkkkkko ',
    '  oooooooooooo  ',
    '                ',
    '                ',
    '                ',
    '                ',
    '                ',
    '                ',
  ],
  pet_oculos_pet: [
    '                ',
    '                ',
    '                ',
    '  oooooooooooo  ',
    ' okkkkoookkkko  ',
    ' okccko okccko  ',
    ' okccko okccko  ',
    ' okkkko okkkko  ',
    '  oooo   oooo   ',
    '                ',
    '                ',
    '                ',
    '                ',
    '                ',
    '                ',
    '                ',
  ],
}

// Se um item novo entrar no catálogo sem desenho, cai num genérico por categoria
// em vez de sumir do cartão.
const FALLBACK = {
  comida: 'pet_racao',
  brinquedo: 'pet_bolinha',
  acessorio: 'pet_coleira',
}

export function drawPetIcon(painter, code, subcategory) {
  const rows = SPRITES[code] || SPRITES[FALLBACK[subcategory]] || SPRITES.pet_racao
  painter.sprite(rows, P, 0, 0, 2)
}

export const PET_ICON_CODES = Object.keys(SPRITES)
